### ISSUE TITLE
请问混合语音和干净语音的文件夹是怎么排列的？

### ISSUE THREAD

**Issue by lvyilan23** [haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement#1]
是按照顺序，mix/1.wav和clean/1.wav是对应的混合和干净语音吗？

**Comment by haoxiangsnr** [comment]
是的。
1. 新建存放带噪语音与纯净语音的目录，在两个目录下分别存放带噪与纯净的同名`.wav`文件。
2. 用这两个目录的路径替换 `config/train/temp.json` 中的相关路径

**Comment by lvyilan23** [comment]
我在mix和train中各放一条语音进行试运行。在终端输入 python train.py -C config/train/temp.json。终端输出到The amount of parameters in the project is 17.579459 million语句后停止运行。这个过程感觉并没有进行训练，因为我在_train_epoch函数中加了输出语句，但并没有相应输出。请问我应该怎么做才能使模型开始训练呢？



------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年8月27日(星期二) 上午8:43
收件人: "haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement"<A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement@noreply.github.com>;
抄送: "lyl"<254467442@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement] 请问混合语音和干净语音的文件夹是怎么排列的？ (#1)




是的。
  
新建存放带噪语音与纯净语音的目录，在两个目录下分别存放带噪与纯净的同名.wav文件。
 
用这两个目录的路径替换 config/train/temp.json 中的相关路径

**Comment by lvyilan23** [comment]
不好意思我刚刚发现我开始为了跑通，在train前加了exit()函数。但是我又遇到了新问题
，我先自己解决一下。麻烦您了，谢谢！

**Comment by haoxiangsnr** [comment]
嗯，不客气
