### ISSUE TITLE
How is it supposed to do inference?

### ISSUE THREAD

**Issue by betegon** [haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement#10]
Hi @haoxiangsnr 

This repo looks so cool.
How could I try your model to do an inference (i.e., clean a noisy .wav file)?

Thank you.

**Comment by haoxiangsnr** [comment]
Hi, I just uploaded the inference configuration file.

you need to:

1. Refer to the existing "config/enhancement/Non-Stationary-Datasets.json" file and write your own inference configuration file in the "config/enhancement/" directory.
2. Run enhancement.py, the parameters of the inference stage can refer to [here](https://github.com/haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement/blob/master/enhancement.py#L103).

**Comment by betegon** [comment]
Thank you for your quickly response,

I will have a look there!

One more question. You have a lot of speech enhancement repositories, which of them is the best for typical background noise?

**Comment by haoxiangsnr** [comment]
CRN is the most suitable, with good performance and small model parameters.
