### ISSUE TITLE
final pesq and stoi

### ISSUE THREAD

**Issue by cst781** [haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement#16]
how many epoch does it need to get the best score of pesq and stoi？I use the testset of noisy speech dataset as the validation set

，but  the pesq of it remains 1.90， would it be something wrong？

**Comment by Ywz2018** [comment]
I encounter the same problems too. However, I got a high score when I trained the network for the first time, but its score dropped significantly when I trained it a year later. Both TIMIT and Noisex92 are used.
