### ISSUE TITLE
关于内存释放的问题

### ISSUE THREAD

**Issue by lvyilan23** [haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement#2]
1.我在运行的过程中，每训练几个epoch，内存占用就会增加1G。但我不是很熟悉pytorch，请问是哪里增加了内存占用，如何释放呢。
2.for mixture, clean, nframes_list, _ in self.train_dataloader， 这四个参数对应data_loader中的哪些参数呢？我没有找到相关代码。
3.我想计算SSNR指标，需要窗长作为参数。请问是 filter_length 这个参数吗
4.我用1500条TIMIT语音(约3秒)作为数据集，训练只需要25秒左右，请问这个速度是正常的吗？
**抱歉问题可能有点多，如果您忙的话可以只回答第一个问题，谢谢！！**

**Comment by lvyilan23** [comment]
另外请问您训练了大概多少轮 才能达到README中的数据呢

**Comment by haoxiangsnr** [comment]
1. 不好意思，这种情况我暂时没有遇到。我使用GPU进行训练，内存在每轮开始时会增强，结束当前轮后会释放一些，但总体保持恒定。
2. DataLoader的返回值定义在[这里](https://github.com/haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement/blob/master/dataset/wav_dataset.py#L60)，其中：
- `mixture`：带噪语音
- `clean`：带噪语音对应的纯净语音
- `nframes_list`：当前语音进行STFT变换后的帧数。一个batch内会容纳多条长度不等的语音，为了能够使用GPU进行训练，我会按照最长的语音pad同一batch内较短的语音，之后进行STFT变换，batch内的所有语音都得到相同帧数的语谱图，此时可以放入GPU中训练。但后续在计算带噪语音与纯净语音的语谱图损失时，需要根据每条语音的`nframes_list`参数来获知语音pad前的帧数，这样计算损失才合理。
- `_`：这个参数为当前语音的文件名，用于验证集的可视化。在训练时不需要，所以使用`_`。
3. 是的，见[这里](https://github.com/haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement/blob/master/trainer/base_trainer.py#L24)。这个项目主要是为了复现论文，如果你想使用其他窗大小，可能会出现一些需要你自行解决的问题。
4. 非常正常，CRN网络的参数量并不大。
5. 较大的数据集（100小时）在训练20轮左右就可以收敛。表现在验证集的PESQ与STOI不再增加
