### ISSUE TITLE
model/loss.py 中的 mse_loss_for_variable_length_data 损失计算的问题

### ISSUE THREAD

**Issue by zhangqi3552** [haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement#25]
Hello，近期在跑您的 CRN 代码时（/trainer/causal_trainer.py + mse_loss_for_variable_length_data）发现，模型输出 size 为 [B, 1, F, T]，loss 中 计算了一个 binary_mask，size 为 [B, 1, T] 的全 1 张量，并通过 [B, 1, F, T] * [B, 1, T] = [B, B, F, T]，的方式将模型输出 copy 了 B 份，请问为什么这样做？扩大损失嘛？

**Comment by SutirthaChakraborty** [comment]
any solution?

**Comment by SutirthaChakraborty** [comment]
How do we modify the loss function for  real and imaginary part
Shape input shape tensors (64,120,201,2) 
64 batch, 120 frames ,201 frequency bins and 2 number of channel (real and imaginary)

**Comment by zhangqi3552** [comment]
Consideration the computation cost, I remove the part of binary_mask, and directly calculate the loss with tensor shape [B, C, F, T]

**Comment by SutirthaChakraborty** [comment]
can you send me a message on my [mail](sutirtha38@gmail.com)? I want to [implement this paper](https://ieeexplore.ieee.org/document/9949329). I needed some help.
