### ISSUE TITLE
关于FFT问题

### ISSUE THREAD

**Issue by jingxuan9862** [haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement#3]
你好， 请问为什么在计算混合信号和纯净信号的fft 和ifft 时， 不是调用一些现成的包， 而是用torch.nn.function.conv1d / conv_transpose1d函数 ？而且直观理解上好像是把傅里叶变换的公式分不同部分进行了求解， 这样是为了加速运算吗？ 有点不理解,望解答。

**Comment by haoxiangsnr** [comment]
您留意到的这个文件并未原创，是[torch-stft](https://github.com/pseeth/torch-stft/blob/master/torch_stft/stft.py) 与 [tacotron2](https://github.com/NVIDIA/tacotron2/blob/master/stft.py) 中的实现。

使用这种实现是为了加速，它们可以调用 GPU 直接对一个 batch 的数据进行短时傅里叶变换。
