### ISSUE TITLE
关于代码的一些问题

### ISSUE THREAD

**Issue by lvyilan23** [haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement#4]
1.最后一层论文中使用了softplus，但是代码中用了relu
2.trainer.py中，_validation_epoch使用了mask操作，但训练时并没用使用。训练和验证时映射还是掩码是否应保持一致呢？

**Comment by haoxiangsnr** [comment]
1. 这是项目与论文存在的偏差之一。网络的映射对象为幅度频谱，最终的输出需要大于 0。文中的 Softplus 是略微平滑的 ReLU，它们都可以将 (负无穷，正无穷) 的数非线性变换至 [0, 正无穷)，性能差别很小，考虑到后续部署的问题，使用了 ReLU。
2. 请留意损失函数的[定义](https://github.com/haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement/blob/master/model/loss.py#L5)，在训练和验证部分都使用了这个损失函数。训练样本和测试样本都是变长的，后续在验证部分[计算 mask](https://github.com/haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement/blob/master/trainer/trainer.py#L101)，仅仅是为了使用 GPU 一次性增强多个样本。
