### ISSUE TITLE
关于enhancement.py

### ISSUE THREAD

**Issue by LucySha** [haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement#5]
你好，请问enhancement中的config 里json配置文件中为什么还需要clean——dataset？我的理解是由noisy——dataset直接就可以生成clean

**Comment by haoxiangsnr** [comment]
哈哈，这里历史遗留与懒惰的问题。你可以将 enhancement.py 中的 mixture_dataset 与 clean_dataset 设置为相同的目录，并不会影响你正常增强语音。

我会在下周晚些时候将这个问题修复。

**Comment by LucySha** [comment]
@haoxiangsnr 哈哈，谢谢您的及时回复，我按照这个思路继续运行，load模型的时候会报错mismatch,coping a param with shape torch.Size([32,1,2,3]) from checkpoint, the shape in current model is torch.size([32,1,1,3])

**Comment by LucySha** [comment]
@haoxiangsnr 感谢您的及时回复，在运行enhancement到 stft.transform（line 85）会出现core dumped 定位到是cpu/gpu的问题

**Comment by haoxiangsnr** [comment]
你可以将[这行代码](https://github.com/haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement/blob/master/enhancement.py#L32)注释掉，将下一行取消注释，应该就可以正常执行了。

后续我会进一步完善这个脚本。

**Comment by LucySha** [comment]
@haoxiangsnr 关于cpu和gpu的问题我为了速度快点我统一改成了gpu，我用的THCHS30进行处理，自行加噪得到的mixture，训练了30epoch进行enhancement时，发现结果更差了，我的输入音频时16kHz， 16bit的，请问这个问题是由于什么造成的呢？train.json中mixture：输入的是训练含噪语音， clean：输入的是训练干净语音。

**Comment by haoxiangsnr** [comment]
验证集的表现怎么样呢，验证集的STOI与PESQ是否正常？

你可以通过 tensorboard 来查看。

**Comment by haoxiangsnr** [comment]
Warning 信息表示从频谱重建后的语音超过了 `(-1, 1)` 的范围，所以被截去了部分。这个只有在网络上训练初期才会出现的问题，是因为映射不好的原因。

你可以使用 32bit 的数据尝试一下。可以对语音进行预处理，或者修改 `wav_dataset.py` 部分的代码。

**Comment by LucySha** [comment]
@haoxiangsnr 您好，有个问题想请教您，降噪后的音频相比于clean的音频会有失真现象，对比二者的频谱可以明显发现降噪后音频共振峰相对于clean没有那么清晰，怎样才能减小这种失真现象，复原共振峰？

**Comment by haoxiangsnr** [comment]
不好意思，最近在外参会。

在我进行的实验中，并没有留意到CRN会有明显的弱点。这种情况可能和你数据集有关，可能你的数据集本身就很有难度。事实上，谐波结构本身就是很难恢复的，尤其当语音处于低信噪比时，这本就是语音增强中的难题。你可以对比一下其他的典型方法（TasNet，TCNN，Wave-U-Net，BiLSTM等），看看它们是否能在你当前的数据集上更好的复原谐波。如果有方法可以较好的复原，那你可以分析它们的网络结构与特征变换过程，看看它们为什么可以完成。

**Comment by LucySha** [comment]
@haoxiangsnr 好的，非常感谢您，我会尝试一下其他的方法对结果进行对比的。

**Comment by haoxiangsnr** [comment]
不客气的。

**Comment by ARKEYTECT** [comment]
你好请问你的输入输出有做标准化么？
