### ISSUE TITLE
网络输入问题

### ISSUE THREAD

**Issue by HTT1995** [haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement#6]
请问网络的输入是多少帧，对应输出是多少帧，【batch_size，in_c，T, nfft】是输入的维度，我做过实验，按照论文中的数据，也就是输入是【batch_size,1,500,256】输出也是一样,但是结果并不理想，请问你这个实验是以多少帧作为一个batch，也就是T设置的多少，我认为500是不是太多了

**Comment by haoxiangsnr** [comment]
不好意思，不是太明白你的问题。

CRN输入的帧数没有限制，输出的帧数与输入的帧数相同。

**Comment by HTT1995** [comment]
您实验的设置是通常输入多少帧呢

**Comment by HTT1995** [comment]
因为CRNN里cnn是二维卷积，所以需要一定的帧数才能进行卷积，如果是一帧1*256，那就没办法跑网络了，所以我想知道通常设置是多少帧作为输入

**Comment by haoxiangsnr** [comment]
在CRN中，一个batch内会容纳多条长度不等的语音，为了能够使用GPU进行训练，我会按照最长的语音pad同一batch内较短的语音，之后进行STFT变换，batch内的所有语音都得到相同帧数的语谱图，此时可以放入GPU中训练。

留意这个函数：https://github.com/haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement/blob/master/train.py#L30

**Comment by HTT1995** [comment]
奥，我知道了，意思是一个batch里就是多条语音的频谱，按最长的进行补零

**Comment by haoxiangsnr** [comment]
嗯，是的

**Comment by HTT1995** [comment]
好的，谢谢，那您是对整个语音数据库进行padding还是每次只对一个batch里的语音，如果只是对一个batch里的进行pad对齐，那么不同的batch会有不同的频谱长度了，那卷积后的长度如何保持一致的

**Comment by haoxiangsnr** [comment]
1. “那您是对整个语音数据库进行padding还是每次只对一个batch里的语音”
答：针对一个`batch`进行`pad`。
2. “如果只是对一个batch里的进行pad对齐，那么不同的batch会有不同的频谱长度了，那卷积后的长度如何保持一致的”
答：是的，不同的 `batch` 有不同的长度。不同 `batch` 内的长度并不需要一致。
建议你参考这里的代码：https://github.com/haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement/blob/master/trainer/trainer.py#L33

**Comment by m1054432257** [comment]
> 请问网络的输入是多少帧，对应输出是多少帧，【batch_size，in_c，T, nfft】是输入的维度，我做过实验，按照论文中的数据，也就是输入是【batch_size,1,500,256】输出也是一样,但是结果并不理想，请问你这个实验是以多少帧作为一个batch，也就是T设置的多少，我认为500是不是太多了



> 请问网络的输入是多少帧，对应输出是多少帧，【batch_size，in_c，T, nfft】是输入的维度，我做过实验，按照论文中的数据，也就是输入是【batch_size,1,500,256】输出也是一样,但是结果并不理想，请问你这个实验是以多少帧作为一个batch，也就是T设置的多少，我认为500是不是太多了

请问网络输入的帧数是多少，也就是T
