### ISSUE TITLE
代码运行中的一些问题。

### ISSUE THREAD

**Issue by JH2018-2021** [haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement#7]
你好，可以帮忙看下这个问题出现的原因吗？
[555](https://user-images.githubusercontent.com/52705998/68528159-f78d5a80-0329-11ea-9e9b-d7d66183ec91.png)
因为没有GPU，我就对json文件进行如下修改：  "n_gpu": 0,"use_cudnn": false,。我使用的是window10系统，spyder编辑器。

**Comment by JH2018-2021** [comment]
问题修改过来了，第一次用torch。

**Comment by haoxiangsnr** [comment]
好的
