### ISSUE TITLE
验证过程的问题

### ISSUE THREAD

**Issue by JH2018-2021** [haoxiangsnr/A-Convolutional-Recurrent-Neural-Network-for-Real-Time-Speech-Enhancement#8]
您好，在训练时候可以正常进行，但是现在在验证过程中出现一个问题，下面是我的报错信息。
![1](https://user-images.githubusercontent.com/52705998/68569774-efecc380-0499-11ea-9c8e-58bd4b348d0f.png)
您可以帮忙解答下吗？
制作数据集部分我使用的是您另一个库里的代码生成的带噪信号以及干净语音。
谢谢您！

**Comment by JH2018-2021** [comment]
![image](https://user-images.githubusercontent.com/52705998/68571580-41974d00-049e-11ea-9ed8-5c3716173ce0.png)
用的是这个代码生成的数据

**Comment by haoxiangsnr** [comment]
很抱歉，我没有办法通过这张截图明确你遇到的问题。请你确定一下：
1. 进入训练集和测试集对应的目录，听一下语音是否正常。如果不正常，请使用[这个库](https://github.com/microsoft/MS-SNSD)重新合成。
2. `cd`到配置文件（`config/**/*.json`）中`save_location`参数对应的目录，之后运行 `tensorboard --logdir ./`。根据命令行中提示的地址和端口访问`TensorBoard`前端网页，查看`AUDIO`选项卡下的语音是否可以被听清，语音是否为空。
3. 将训练集中的部分语音作为测试集，看是否可以正常进行验证。为了方便快速测试，你可以将配置文件中`train_dataset['args']['limit']`参数设置为`100`。表示使用训练集中的前`100`句语音进行训练。

**Comment by JH2018-2021** [comment]
好的，谢谢您的回复。
